<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
    <AssemblyName>AccountingETL</AssemblyName>
    <RootNamespace>AccountingETL.App</RootNamespace>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\core\AccountingETL.Core.csproj" />
    <ProjectReference Include="..\adapters\express\AccountingETL.Adapters.Express.csproj" />
    <ProjectReference Include="..\adapters\postgresql\AccountingETL.Adapters.PostgreSQL.csproj" />
    <ProjectReference Include="..\adapters\erpnext\AccountingETL.Adapters.ErpNext.csproj" />

    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
  </ItemGroup>

</Project>
